### ISSUE TITLE
Task error on bot startup

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1576]
Seen on dev.

    Task exception was never retrieved
    future: <Task finished coro=<background_task_spoiler_season() done, defined at /Users/bakert/pd/discordbot/bot.py:169> exception=TooFewItemsException("Expected `1` and got `0` with `{'Lost Vale'}`.  missing=`{'Lost Vale'}`",)>
    Traceback (most recent call last):
      File "/Users/bakert/pd/magic/oracle.py", line 37, in valid_name
        return cards[0].name
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/bakert/pd/discordbot/bot.py", line 175, in background_task_spoiler_season
        oracle.valid_name(c['name'])
      File "/Users/bakert/pd/magic/oracle.py", line 39, in valid_name
        raise InvalidDataException('Did not find any cards looking for `{name}`'.format(name=name))
    shared.pd_exception.InvalidDataException: Did not find any cards looking for `Dowsing Dagger // Lost Vale`

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
        result = coro.send(None)
      File "/Users/bakert/pd/discordbot/bot.py", line 177, in background_task_spoiler_season
        oracle.insert_scryfall_card(c)
      File "/Users/bakert/pd/magic/oracle.py", line 203, in insert_scryfall_card
        CARDS_BY_NAME[name] = load_card(name)
      File "/Users/bakert/pd/magic/oracle.py", line 42, in load_card
        return load_cards([name])[0]
      File "/Users/bakert/pd/magic/oracle.py", line 58, in load_cards
        raise TooFewItemsException('Expected `{namelen}` and got `{rslen}` with `{names}`.  missing=`{missing}`'.format(namelen=len(names), rslen=len(rs), names=names, missing=missing))
    shared.pd_exception.TooFewItemsException: Expected `1` and got `0` with `{'Lost Vale'}`.  missing=`{'Lost Vale'}`

**Comment by bakert** [comment]
lost vale
arlinn, embraced by the moon
lord of lineage

...

something going on with the reverse side of double-faced cards. and we end up with them in the database twice as the end of this.

    mysql> SELECT COUNT(*), name FROM face GROUP BY name HAVING COUNT(*) > 1;
    +----------+--------------------------------+
    | COUNT(*) | name                           |
    +----------+--------------------------------+
    |        2 | Adanto, the First Fort         |
    |        2 | Archangel Avacyn               |
    |        2 | Arguel's Blood Fast            |
    |        2 | Arlinn Kord                    |
    |        2 | Arlinn, Embraced by the Moon   |
    |        2 | Avacyn, the Purifier           |
    |        2 | Azcanta, the Sunken Ruin       |
    |        2 | Bloodline Keeper               |
    |        2 | Brisela, Voice of Nightmares   |
    |        2 | Chittering Host                |
    |        2 | Conqueror's Foothold           |
    |        2 | Conqueror's Galleon            |
    |        2 | Dowsing Dagger                 |
    |        2 | Growing Rites of Itlimoc       |
    |        2 | Hanweir, the Writhing Township |
    |        2 | Itlimoc, Cradle of the Sun     |
    |        2 | Legion's Landing               |
    |        2 | Lord of Lineage                |
    |        2 | Lost Vale                      |
    |        2 | Primal Amulet                  |
    |        2 | Primal Wellspring              |
    |        2 | Search for Azcanta             |
    |        2 | Spires of Orazca               |
    |        2 | Spitfire Bastion               |
    |        2 | Temple of Aclazotz             |
    |        2 | Thaumatic Compass              |
    |        2 | Treasure Cove                  |
    |        2 | Treasure Map                   |
    |        2 | Vance's Blasting Cannons       |
    +----------+--------------------------------+
    29 rows in set (0.06 sec)

This is just straight up BS so first thing I"m going to do is delete the dupes and add a UNIQUE constraint on face.name

**Comment by bakert** [comment]
The reason we don't have UNIQUE on face.name is because of meld cards. The meld side is two faces but they both have the same name (kinda). It's ugly but it's probably necessary.

**Comment by bakert** [comment]
This still seems mostly terrible to me but I've stopped the errors and hopefully sane-ified the database so that we don't get dupes when fixing up insert_scryfall_card to work with the new _card_cache.
