### ISSUE TITLE
Make decksite threadsafe, so we can move to uwsgi.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#2062]
We really need to get this working.

`decksite.ini`:
```
[uwsgi]
plugin = python3
http-socket = 127.0.0.1:5000
user = discord
uid = discord
chdir = /home/discord/decksite/
wsgi-file = /home/discord/decksite/decksite.wsgi
processes = 4
threads = 2
stats = 127.0.0.1:5001
lazy-apps = true
```

**Comment by bakert** [comment]
Can we remember what the issues were? Apparently you can run the devserver multithreaded or with multiple process via:

    APP.run(host='0.0.0.0', threaded=True)

or:

    APP.run(host='0.0.0.0', process=10)

I assume the issue is stuff like `multiverse.init()` that uses "global" variables and assumes once they are set up all is well. But maybe it was something else and those are all set up per-request. Or maybe it was just race conditions when more than one thread/process thought it was its job to update the database, etc.

Whatever the affected parts we should push them into the db or maybe memcache.

**Comment by bakert** [comment]
Just battering it with about 15 requests with `processes=10` wasn't enough to surface any errors.

**Comment by silasary** [comment]
Let me fire it up on prod and see

**Comment by silasary** [comment]
It looks like whatever issue we had earlier is fixed?

**Comment by silasary** [comment]
Nope.  Still there.
```
Nov 23 19:37:45 katelyngigante uwsgi[12963]: [2017-11-23 19:37:45,151] ERROR in app: Exception on /archetypes/67/ [GET]
Nov 23 19:37:45 katelyngigante uwsgi[12963]: Traceback (most recent call last):
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./shared/database_mysql.py", line 44, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     self.cursor.execute(sql, args)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     self.errorhandler(self, exc, value)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     raise errorvalue
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     res = self._query(query)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     rowcount = self._do_query(q)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     db.query(q)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 270, in query
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     _mysql.connection.query(self, query)
Nov 23 19:37:45 katelyngigante uwsgi[12963]: _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
Nov 23 19:37:45 katelyngigante uwsgi[12963]: The above exception was the direct cause of the following exception:
Nov 23 19:37:45 katelyngigante uwsgi[12963]: Traceback (most recent call last):
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     response = self.full_dispatch_request()
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     rv = self.handle_user_exception(e)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     reraise(exc_type, exc_value, tb)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     raise value
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     rv = self.dispatch_request()
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     return self.view_functions[rule.endpoint](**req.view_args)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/cache.py", line 64, in decorated_function
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     response = make_response(f(*args, **kwargs))
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/main.py", line 92, in archetype
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     view = Archetype(a, archs.load_archetypes_deckless_for(a.id), archs.load_matchups(a.id))
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/data/archetype.py", line 149, in load_matchups
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     return [Container(m) for m in db().execute(sql, [rotation.last_rotation().timestamp()] * 4 + [archetype_id])]
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./shared/database_mysql.py", line 53, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e)) from e
Nov 23 19:37:45 katelyngigante uwsgi[12963]: shared.pd_exception.DatabaseException: Failed to execute `
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         SELECT
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             oa.id, oa.name,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN d.created_date < %s THEN 0 WHEN dm.games = 2 THEN 1 ELSE 0 END) AS `season_wins`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN d.created_date < %s THEN 0 WHEN odm.games = 2 THEN 1 ELSE 0 END) AS `season_losses`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN d.created_date < %s THEN 0 WHEN dm.games = odm.games THEN 1 ELSE 0 END) AS `season_draws`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             IFNULL(ROUND(AVG(CASE WHEN d.created_date < %s THEN NULL WHEN dm.games = 2 THEN 1 WHEN odm.games = 2 THEN 0 END) * 100, 1), '') AS `s
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN dm.games = 2 THEN 1 ELSE 0 END) AS `all_wins`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN odm.games = 2 THEN 1 ELSE 0 END) AS `all_losses`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN dm.games = odm.games THEN 1 ELSE 0 END) AS `all_draws`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             IFNULL(ROUND(AVG(CASE WHEN dm.games = 2 THEN 1 WHEN odm.games = 2 THEN 0 END) * 100, 1), '') AS `all_win_percent`
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         FROM
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             archetype AS a
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck AS d
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             d.archetype_id IN (SELECT descendant FROM archetype_closure WHERE ancestor = a.id)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck_match AS dm
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             d.id = dm.deck_id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck_match AS odm
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             dm.match_id = odm.match_id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             AND odm.deck_id <> d.id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck AS od
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             od.id = odm.deck_id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             archetype AS oa
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             od.archetype_id IN (SELECT descendant FROM archetype_closure WHERE ancestor = oa.id)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         WHERE
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             a.id = %s
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         GROUP BY
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             oa.id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ORDER BY
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             `season_wins` DESC, `all_wins` DESC
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     ` with `[1506668400.0, 1506668400.0, 1506668400.0, 1506668400.0, 67]` because of `(2013, 'Lost connection to MySQL server during query')`
Nov 23 19:37:45 katelyngigante uwsgi[12963]: Traceback (most recent call last):
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./shared/database_mysql.py", line 44, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     self.cursor.execute(sql, args)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     self.errorhandler(self, exc, value)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     raise errorvalue
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     res = self._query(query)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     rowcount = self._do_query(q)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     db.query(q)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 270, in query
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     _mysql.connection.query(self, query)
Nov 23 19:37:45 katelyngigante uwsgi[12963]: _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
Nov 23 19:37:45 katelyngigante uwsgi[12963]: The above exception was the direct cause of the following exception:
Nov 23 19:37:45 katelyngigante uwsgi[12963]: shared.pd_exception.DatabaseException: Failed to execute `
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         SELECT
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             oa.id, oa.name,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN d.created_date < %s THEN 0 WHEN dm.games = 2 THEN 1 ELSE 0 END) AS `season_wins`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN d.created_date < %s THEN 0 WHEN odm.games = 2 THEN 1 ELSE 0 END) AS `season_losses`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN d.created_date < %s THEN 0 WHEN dm.games = odm.games THEN 1 ELSE 0 END) AS `season_draws`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             IFNULL(ROUND(AVG(CASE WHEN d.created_date < %s THEN NULL WHEN dm.games = 2 THEN 1 WHEN odm.games = 2 THEN 0 END) * 100, 1), '') AS `s
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN dm.games = 2 THEN 1 ELSE 0 END) AS `all_wins`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN odm.games = 2 THEN 1 ELSE 0 END) AS `all_losses`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             SUM(CASE WHEN dm.games = odm.games THEN 1 ELSE 0 END) AS `all_draws`,
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             IFNULL(ROUND(AVG(CASE WHEN dm.games = 2 THEN 1 WHEN odm.games = 2 THEN 0 END) * 100, 1), '') AS `all_win_percent`
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         FROM
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             archetype AS a
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck AS d
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             d.archetype_id IN (SELECT descendant FROM archetype_closure WHERE ancestor = a.id)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck_match AS dm
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             d.id = dm.deck_id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck_match AS odm
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             dm.match_id = odm.match_id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             AND odm.deck_id <> d.id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             deck AS od
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             od.id = odm.deck_id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         INNER JOIN
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             archetype AS oa
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ON
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             od.archetype_id IN (SELECT descendant FROM archetype_closure WHERE ancestor = oa.id)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         WHERE
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             a.id = %s
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         GROUP BY
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             oa.id
Nov 23 19:37:45 katelyngigante uwsgi[12963]:         ORDER BY
Nov 23 19:37:45 katelyngigante uwsgi[12963]:             `season_wins` DESC, `all_wins` DESC
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     ` with `[1506668400.0, 1506668400.0, 1506668400.0, 1506668400.0, 67]` because of `(2013, 'Lost connection to MySQL server during query')`
```

**Comment by bakert** [comment]
See #2183 #2184 #2185 #2142 #2138 #2137 for issues encountered while transitioned. Mostly db-related.

**Comment by bakert** [comment]
We did it!
