### ISSUE TITLE
AttributeError: 'Deck' object has no attribute 'colored_symbols'

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#2091]
```
Nov 23 19:37:45 katelyngigante uwsgi[12963]: AttributeError: 'Deck' object has no attribute 'colored_symbols'
Nov 23 19:37:45 katelyngigante uwsgi[12963]: During handling of the above exception, another exception occurred:
Nov 23 19:37:45 katelyngigante uwsgi[12963]: Traceback (most recent call last):
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     response = self.full_dispatch_request()
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     rv = self.handle_user_exception(e)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     reraise(exc_type, exc_value, tb)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     raise value
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     rv = self.dispatch_request()
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     return self.view_functions[rule.endpoint](**req.view_args)
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/cache.py", line 64, in decorated_function
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     response = make_response(f(*args, **kwargs))
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/main.py", line 64, in card
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     c = cs.load_card(oracle.valid_name(name.replace('+', ' ')))
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/data/card.py", line 47, in load_card
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     c.decks = deck.load_decks('d.id IN (SELECT deck_id FROM deck_card WHERE card = {name})'.format(name=sqlescape(name)))
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./decksite/data/deck.py", line 79, in load_decks
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     d.colored_symbols = json.loads(d.colored_symbols or '[]')
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./shared/container.py", line 13, in __getattr__
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     raise AttributeError(k)
Nov 23 19:37:45 katelyngigante uwsgi[12963]: AttributeError: colored_symbols
Nov 23 19:37:45 katelyngigante uwsgi[12963]: Traceback (most recent call last):
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./shared/container.py", line 8, in __getattr__
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     return self[k]
Nov 23 19:37:45 katelyngigante uwsgi[12963]: KeyError: 'colored_symbols'
Nov 23 19:37:45 katelyngigante uwsgi[12963]: During handling of the above exception, another exception occurred:
Nov 23 19:37:45 katelyngigante uwsgi[12963]: Traceback (most recent call last):
Nov 23 19:37:45 katelyngigante uwsgi[12963]:   File "./shared/container.py", line 11, in __getattr__
Nov 23 19:37:45 katelyngigante uwsgi[12963]:     return object.__getattribute__(self, k)
```

**Comment by bakert** [comment]
Interesting. A deck that's loaded from the db should always have colored_symbols even if it is `None` because of `SELECT ... cache.colored_symbols ...` in deck.load_decks.

The only other place we construct a Deck object is in decklist.vivify which isn't called when loading "decks containing card X".

Does your db's `deck_cache` table have a `colored_symbols` column?

**Comment by bakert** [comment]
Closing this as a one-off/dev env issue but feel free to reopen if you see it again.
