### ISSUE TITLE
Failure repriming cache on prod due to unicode elipses (!)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3831]
```
discord@katelyngigante:~/decksite> python3 run.py maintenance reprime_cache
Fetching http://whatsinstandard.com/api/v5/sets.json (cache ok)
Fetching https://mtgjson.com/json/version.json (cache ok)
Traceback (most recent call last):
  File "run.py", line 74, in <module>
    run()
  File "run.py", line 29, in run
    task(sys.argv)
  File "run.py", line 72, in task
    s.ad_hoc()
  File "/home/discord/decksite/decksite/maintenance/reprime_cache.py", line 10, in ad_hoc
    deck.prime_cache(d)
  File "/home/discord/decksite/decksite/data/deck.py", line 227, in prime_cache
    set_legality(d)
  File "/home/discord/decksite/decksite/data/deck.py", line 142, in set_legality
    d.legal_formats = legality.legal_formats(d)
  File "/home/discord/decksite/magic/legality.py", line 10, in legal_formats
    init()
  File "/home/discord/decksite/magic/legality.py", line 83, in init
    print('Updating Legalities\u2026')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 19: ordinal not in range(128)
```

**Comment by bakert** [comment]
```
PYTHONENCODING=utf-8 python3 run.py maintenance reprime_cache
```

also does not work.

**Comment by bakert** [comment]
Adding

```
# coding=utf-8
```

to legality.py also did not work.

**Comment by bakert** [comment]
Removing the unicode char did work, obviously.

ae06b51c reverts using unicode chars for now but I'll leave this open because it's dumb.

**Comment by silasary** [comment]
Adding `sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())` to the top of run.py should fix this.

**Comment by silasary** [comment]
Also, worth noting that the ENV var we want is `PYTHONIOENCODING` not `PYTHONENCODING`

**Comment by bakert** [comment]
6938a577.
