### ISSUE TITLE
Price grabber is failing – something to do with sqlite changes

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4127]
```
Creating database ./cards.sqlite
Traceback (most recent call last):
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database_mysql.py", line 45, in execute
    self.cursor.execute(sql, args)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near './cards.sqlite' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database_mysql.py", line 28, in __init__
    self.execute("USE {db}".format(db=db))
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database_mysql.py", line 56, in execute
    raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e))
shared.pd_exception.DatabaseException: Failed to execute `USE ./cards.sqlite` with `[]` because of `(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near './cards.sqlite' at line 1")`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database_mysql.py", line 45, in execute
    self.cursor.execute(sql, args)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near './cards.sqlite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../Penny-Dreadful-Discord-Bot/run.py", line 77, in <module>
    run()
  File "../Penny-Dreadful-Discord-Bot/run.py", line 27, in run
    price_grabber.run()
  File "/home/discord/Penny-Dreadful-Discord-Bot/price_grabber/price_grabber.py", line 19, in run
    multiverse.init()
  File "/home/discord/Penny-Dreadful-Discord-Bot/magic/multiverse.py", line 20, in init
    if pkg_resources.parse_version(current_version) > pkg_resources.parse_version(database.mtgjson_version()):
  File "/home/discord/Penny-Dreadful-Discord-Bot/magic/database.py", line 34, in mtgjson_version
    return db().value('SELECT version FROM version', [], '0')
  File "/home/discord/Penny-Dreadful-Discord-Bot/magic/database.py", line 20, in db
    context.magic_database = get_database(configuration.get('magic_database'))
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database.py", line 4, in get_database
    return database_mysql.MysqlDatabase(location)
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database_mysql.py", line 31, in __init__
    self.execute('CREATE DATABASE {db} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'.format(db=db))
  File "/home/discord/Penny-Dreadful-Discord-Bot/shared/database_mysql.py", line 56, in execute
    raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e))
shared.pd_exception.DatabaseException: Failed to execute `CREATE DATABASE ./cards.sqlite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci` with `[]` because of `(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near './cards.sqlite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' at line 1")`
```

**Comment by silasary** [comment]
Config file was:
```
> cat config.json
{
    "web_cache": ".web_cache",
    "card_alias_file": "./card_aliases.tsv",
    "prices_database": "prices",
    "spellfix": "./spellfix",
    "mysql_port": 3306,
    "pricesdb": "./prices.db",
    "mysql_host": "localhost",
    "mysql_passwd": xxxx,
    "mysql_user": xxxx,
    "magic_database": "./cards.sqlite",
    "scratch_dir": ".",
    "slow_query": 60,
    "github_user": null,
    "slow_fetch": 60,
    "cardhoarder_urls": xxxx,
    "whoosh_index_dir": "whoosh_index"
}
```

I have fixed the values for `pricesdb` and `magic_database`, which should hopefully fix things.

**Comment by bakert** [comment]
I think the problem here is the general problem with upgrading multiverse described in #4140. Will reopen if that proves not to be the case.
