### ISSUE TITLE
Gatherling import is currently broken

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#415]
Console Output:

```
Fetching https://mtgjson.com/json/version.json (Last Modified=Wed, 05 Oct 2016 11:02:40 GMT)
Fetching http://gatherling.com/eventreport.php?format=Penny+Dreadful&series=&season=&mode=Filter+Events
Fetching http://gatherling.com/eventreport.php?event=Penny Dreadful Thursdays 1.02
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    run()
  File "run.py", line 25, in run
    m.scrape()
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 22, in scrape
    tournament(url, name)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 32, in tournament
    dt = dtutil.parse(date_s, '%d %B %Y', dtutil.GATHERLING_TZ)
  File "/home/discord/decksite/shared/dtutil.py", line 25, in parse
    dt = datetime.datetime.strptime(s, date_format)
  File "/usr/lib64/python3.5/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib64/python3.5/_strptime.py", line 340, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  17:00
```

**Comment by silasary** [comment]
We're calling `datetime.datetime.strptime()` with `data_string = '27 October 2016 17:00', format = '%d %B %Y'`
