### ISSUE TITLE
Art command failing with OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4265]
```
Feb 10 21:13:24 katelyngigante bash[17905]: Ignoring exception in on_message
Feb 10 21:13:24 katelyngigante bash[17905]: Traceback (most recent call last):
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client.py", line 200, in _request
Feb 10 21:13:24 katelyngigante bash[17905]:     resp = req.send(conn.writer, conn.reader)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 490, in send
Feb 10 21:13:24 katelyngigante bash[17905]:     writer.set_tcp_cork(True)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/parsers.py", line 274, in set_tcp_cork
Feb 10 21:13:24 katelyngigante bash[17905]:     False)
Feb 10 21:13:24 katelyngigante bash[17905]: OSError: [Errno 9] Bad file descriptor
Feb 10 21:13:24 katelyngigante bash[17905]: The above exception was the direct cause of the following exception:
Feb 10 21:13:24 katelyngigante bash[17905]: Traceback (most recent call last):
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/command.py", line 66, in handle_command
Feb 10 21:13:24 katelyngigante bash[17905]:     await method(Commands, bot, message.channel, args, message.author)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/command.py", line 456, in art
Feb 10 21:13:24 katelyngigante bash[17905]:     await bot.send_image_with_retry(channel, image_file)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/bot.py", line 115, in send_image_with_retry
Feb 10 21:13:24 katelyngigante bash[17905]:     message = await self.client.send_file(channel, image_file, content=text)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/discord/client.py", line 1235, in send_file
Feb 10 21:13:24 katelyngigante bash[17905]:     filename=filename, content=content, tts=tts)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/discord/http.py", line 137, in request
Feb 10 21:13:24 katelyngigante bash[17905]:     r = yield from self.session.request(method, url, **kwargs)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
Feb 10 21:13:24 katelyngigante bash[17905]:     resp = yield from self._coro
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client.py", line 211, in _request
Feb 10 21:13:24 katelyngigante bash[17905]:     raise aiohttp.ClientOSError(*exc.args) from exc
Feb 10 21:13:24 katelyngigante bash[17905]: aiohttp.errors.ClientOSError: [Errno 9] Bad file descriptor
Feb 10 21:13:24 katelyngigante bash[17905]: During handling of the above exception, another exception occurred:
Feb 10 21:13:24 katelyngigante bash[17905]: Traceback (most recent call last):
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/.local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
Feb 10 21:13:24 katelyngigante bash[17905]:     yield from getattr(self, event)(*args, **kwargs)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/bot.py", line 136, in on_message
Feb 10 21:13:24 katelyngigante bash[17905]:     await BOT.on_message(message)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/bot.py", line 42, in on_message
Feb 10 21:13:24 katelyngigante bash[17905]:     await self.respond_to_command(message)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/bot.py", line 59, in respond_to_command
Feb 10 21:13:24 katelyngigante bash[17905]:     await command.handle_command(message, self)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/command.py", line 78, in handle_command
Feb 10 21:13:24 katelyngigante bash[17905]:     print(tb)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/usr/lib64/python3.6/codecs.py", line 377, in write
Feb 10 21:13:24 katelyngigante bash[17905]:     self.stream.write(data)
Feb 10 21:13:24 katelyngigante bash[17905]: OSError: [Errno 9] Bad file descriptor
Feb 10 21:13:24 katelyngigante bash[17905]: Fatal write error on socket transport
Feb 10 21:13:24 katelyngigante bash[17905]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa64091828>
Feb 10 21:13:24 katelyngigante bash[17905]: transport: <_SelectorSocketTransport fd=1 read=polling write=<idle, bufsize=0>>
Feb 10 21:13:24 katelyngigante bash[17905]: Traceback (most recent call last):
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/usr/lib64/python3.6/asyncio/selector_events.py", line 761, in write
Feb 10 21:13:24 katelyngigante bash[17905]:     n = self._sock.send(data)
Feb 10 21:13:24 katelyngigante bash[17905]: OSError: [Errno 9] Bad file descriptor
Feb 10 21:13:24 katelyngigante bash[17905]: Unclosed connection
Feb 10 21:13:24 katelyngigante bash[17905]: client_connection: Connection<('discordapp.com', 443, True)>
Feb 10 21:13:24 katelyngigante bash[17905]: Exception in callback _SelectorTransport._call_connection_lost(OSError(9, 'B...e descriptor'))
Feb 10 21:13:24 katelyngigante bash[17905]: handle: <Handle _SelectorTransport._call_connection_lost(OSError(9, 'B...e descriptor'))>
Feb 10 21:13:24 katelyngigante bash[17905]: Traceback (most recent call last):
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
Feb 10 21:13:24 katelyngigante bash[17905]:     self._callback(*self._args)
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/usr/lib64/python3.6/asyncio/selector_events.py", line 664, in _call_connection_lost
Feb 10 21:13:24 katelyngigante bash[17905]:     self._sock.close()
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/usr/lib64/python3.6/socket.py", line 417, in close
Feb 10 21:13:24 katelyngigante bash[17905]:     self._real_close()
Feb 10 21:13:24 katelyngigante bash[17905]:   File "/usr/lib64/python3.6/socket.py", line 411, in _real_close
Feb 10 21:13:24 katelyngigante bash[17905]:     _ss.close(self)
Feb 10 21:13:24 katelyngigante bash[17905]: OSError: [Errno 9] Bad file descriptor
```

```
Traceback (most recent call last):
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 407, in write_bytes
    result = stream.send(value)
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/helpers.py", line 191, in _gen_form_data
    yield from self._writer.serialize()
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/multipart.py", line 969, in serialize
    yield from part.serialize()
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/multipart.py", line 768, in serialize
    yield from self._maybe_encode_stream(self._serialize_obj())
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/multipart.py", line 781, in _serialize_obj
    return self._serialize_default(obj)
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/multipart.py", line 813, in _serialize_default
    raise TypeError('unknown body part type %r' % type(obj))
TypeError: unknown body part type <class 'bool'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/command.py", line 66, in handle_command
    await method(Commands, bot, message.channel, args, message.author)
  File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/command.py", line 456, in art
    await bot.send_image_with_retry(channel, image_file)
  File "/home/discord/Penny-Dreadful-Discord-Bot/discordbot/bot.py", line 115, in send_image_with_retry
    message = await self.client.send_file(channel, image_file, content=text)
  File "/home/discord/.local/lib/python3.6/site-packages/discord/client.py", line 1235, in send_file
    filename=filename, content=content, tts=tts)
  File "/home/discord/.local/lib/python3.6/site-packages/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/home/discord/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
aiohttp.errors.ClientRequestError: Can not write request body for https://discordapp.com/api/v6/channels/207281932214599682/messages

Reported on Discord by Ellsworth29#9778
```

**Comment by bakert** [comment]
Now tracked elsewhere.
