### ISSUE TITLE
404 visiting /rotation

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4626]
```
Apr 20 19:40:07 katelyngigante uwsgi[21021]: [2018-04-20 19:40:07,507] ERROR in logger: Traceback (most recent call last):
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "./decksite/data/guarantee.py", line 10, in exactly_one
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     return l[0]
Apr 20 19:40:07 katelyngigante uwsgi[21021]: IndexError: list index out of range
Apr 20 19:40:07 katelyngigante uwsgi[21021]: During handling of the above exception, another exception occurred:
Apr 20 19:40:07 katelyngigante uwsgi[21021]: Traceback (most recent call last):
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     rv = self.dispatch_request()
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "./decksite/cache.py", line 71, in decorated_function
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     response = make_response(f(*args, **kwargs))
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "./decksite/main.py", line 89, in person
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     p = ps.load_person(person_id, season_id=g.get('season_id', rot.current_season_num()))
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "./decksite/data/person.py", line 21, in load_person
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     return guarantee.exactly_one(load_people('p.id = {person_id} OR p.mtgo_username = {username}'.format(person_id=person_id, username=username), season_id=season_id))
Apr 20 19:40:07 katelyngigante uwsgi[21021]:   File "./decksite/data/guarantee.py", line 12, in exactly_one
Apr 20 19:40:07 katelyngigante uwsgi[21021]:     raise DoesNotExistException('Did not find an item when expecting one.')
Apr 20 19:40:07 katelyngigante uwsgi[21021]: shared.pd_exception.DoesNotExistException: Did not find an item when expecting one.
```

**Comment by bakert** [comment]
Seems likely seasonizing-related although I can't quite see how off the top of my head.

**Comment by bakert** [comment]
Works on local. On prod we get:

```
Apr 20 20:28:06 katelyngigante uwsgi[21021]: [2018-04-20 20:28:06,009] ERROR in logger: Traceback (most recent call last):
Apr 20 20:28:06 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
Apr 20 20:28:06 katelyngigante uwsgi[21021]:     rv = self.dispatch_request()
Apr 20 20:28:06 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1590, in dispatch_request
Apr 20 20:28:06 katelyngigante uwsgi[21021]:     self.raise_routing_exception(req)
Apr 20 20:28:06 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1573, in raise_routing_exception
Apr 20 20:28:06 katelyngigante uwsgi[21021]:     raise request.routing_exception
Apr 20 20:28:06 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/flask/ctx.py", line 294, in match_request
Apr 20 20:28:06 katelyngigante uwsgi[21021]:     self.url_adapter.match(return_rule=True)
Apr 20 20:28:06 katelyngigante uwsgi[21021]:   File "/home/discord/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
Apr 20 20:28:06 katelyngigante uwsgi[21021]:     raise NotFound()
Apr 20 20:28:06 katelyngigante uwsgi[21021]: werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
```

**Comment by bakert** [comment]
c8732e7.
