### ISSUE TITLE
Gatherling scraper fails

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5024]
````
Fetching https://gatherling.com/deck.php?mode=view&id=58385 (cache ok)
Traceback (most recent call last):
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 241, in lookup
    return decks_by_identifier[gatherling_id]
KeyError: '58174'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 86, in <module>
    run()
  File "run.py", line 31, in run
    task(sys.argv)
  File "run.py", line 79, in task
    s.scrape() # type: ignore
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 27, in scrape
    i = tournament(url, name)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 52, in tournament
    return add_decks(dt, competition_id, final, s)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 93, in add_decks
    add_ids(matches, ds)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 246, in add_ids
    m['right_id'] = lookup(m['right_identifier']).id if m['right_identifier'] else None
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 243, in lookup
    raise InvalidDataException("Unable to find deck with gatherling id '{0}'".format(gatherling_id))
shared.pd_exception.InvalidDataException: Unable to find deck with gatherling id '58174'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f94bb7916a0>
````

**Comment by silasary** [comment]
This is a partially scraped tournament

**Comment by bakert** [comment]
```
DELETE FROM `match` WHERE id IN (SELECT match_id FROM deck_match WHERE deck_id IN (SELECT id FROM deck WHERE competition_id = 495));
DELETE FROM deck WHERE competition_id = 495;
```

and re-run scraper cleared things up.

Might be better to make this more resilient but this sorts things for now.
