### ISSUE TITLE
Scraper fails because of a MySQL error

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#5256]
```
Traceback (most recent call last):
  File "/home/discord/decksite/shared/database.py", line 50, in execute_anything
    return self.execute_with_reconnect(sql, args, fetch_rows)
  File "/home/discord/decksite/shared/database.py", line 66, in execute_with_reconnect
    n = self.cursor.execute(sql, args)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/home/discord/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '' for key 'idx_u_name'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 87, in <module>
    run()
  File "run.py", line 31, in run
    task(sys.argv)
  File "run.py", line 74, in task
    s.scrape() # type: ignore
  File "/home/discord/decksite/decksite/scrapers/bugged_cards.py", line 6, in scrape
    multiverse.update_cache()
  File "/home/discord/decksite/magic/multiverse.py", line 272, in update_cache
    db().execute('CREATE UNIQUE INDEX idx_u_name on _cache_card (name(142))')
  File "/home/discord/decksite/shared/database.py", line 43, in execute
    [n, _] = self.execute_anything(sql, args, False)
  File "/home/discord/decksite/shared/database.py", line 58, in execute_anything
    raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e))
shared.pd_exception.DatabaseException: Failed to execute `CREATE UNIQUE INDEX idx_u_name on _cache_card (name(142))` with `[]` because of `(1062, "Duplicate entry '' for key 'idx_u_name'")`
```

**Comment by silasary** [comment]
@bakert One of your recent changes?

**Comment by bakert** [comment]
Yes that's me. I patched the bad battlebond names so we could add this index but didn't bump schema version. Doh. I'll do it now.

**Comment by bakert** [comment]
Fix is out.
