### ISSUE TITLE
Missing images from /image/

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5267]
```
Errno 2] No such file or directory: '/home/discord/decksite/decksite/./images/words-of-waste.jpg'

Reported on decksite by logged_out```
--------------------------------------------------------------------------------
Request Method: GET
Path: /image/Words of Waste/?
Cookies: {}
Endpoint: image
View Args: {'c': 'Words of Waste'}
Person: logged_out
Referrer: None
Request Data: {}
Host: pennydreadfulmagic.com
Accept-Encoding: gzip
Cf-Ipcountry: US
X-Forwarded-For: 192.30.252.44, 162.158.106.116
Cf-Ray: 4547b1f128cc797f-SEA
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
User-Agent: github-camo (65c9ebe0)
Accept: /
Accept-Language: en-US,en;q=0.5
Via: HTTP/1.1 github-camo (65c9ebe0)
Cf-Connecting-Ip: 192.30.252.44
X-Forwarded-Host: pennydreadfulmagic.com
X-Forwarded-Server: pennydreadfulmagic.com
Connection: Keep-Alive

--------------------------------------------------------------------------------
FileNotFoundError
Stack Trace:
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in call
return self.wsgi_app(environ, start_response)
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/discord/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functionsrule.endpoint
File "./decksite/main.py", line 372, in image
return send_file(path)
File "/home/discord/.local/lib/python3.6/site-packages/flask/helpers.py", line 588, in send_file
file = open(filename, 'rb')

```

**Comment by bakert** [comment]
There are a bunch of these. As we call `acceptable_file` before returning it will take some investigation.

**Comment by bakert** [comment]
The path here is `/home/discord/decksite/decksite/./images/words-of-waste.jpg` which has "decksite" one too many times. Y tho?

**Comment by bakert** [comment]
That is an actual filepath ('decksite' contains a full checkout of the repo and one of the top-level directories is called decksite). But that's not where the (working) words-of-waste.jpg image is.

**Comment by bakert** [comment]
This is kind of weird. (From prod REPL.)

```
>>> from decksite import APP
>>> with APP.app_context():
...     send_file(path)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/discord/.local/lib/python3.6/site-packages/flask/helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/discord/decksite/decksite/./images/words-of-waste.jpg'
>>> open(path, 'rb')
<_io.BufferedReader name='./images/words-of-waste.jpg'>
```

`open` does the right thing in a REPL when called directly but not when called via `send_file`. The "current directory" is wrong in the `send_file` version. But some of our `send_file` calls do the *right* thing otherwise the endpoint wouldn't be working at all.

**Comment by bakert** [comment]
Actually I think maybe every image IS broken rn. I can no longer get the prod version to give me an image for anything.

**Comment by bakert** [comment]
So, I think I have it, `store` saves them (and declares them send-able) relative to monolith root because it's a monolith thing.

`send_file` then tries to send from a decksite-relative root because it's decksite/flask-specific and that's the mismatch.

Fix is probably to make an absolute path immediately prior to passing into `send_file`?

**Comment by bakert** [comment]
a33df74a.
