### ISSUE TITLE
i18n generation failure kills maintenance all job

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5522]
```
[2018-10-10 02:33:32,229] WARNING in logger: Saving to shared_web/translations/da/LC_MESSAGES/messages.po
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    run()
  File "run.py", line 33, in run
    task(sys.argv)
  File "run.py", line 67, in task
    run_all_tasks(module)
  File "run.py", line 93, in run_all_tasks
    s.run() # type: ignore
  File "/home/discord/decksite/maintenance/update_translations.py", line 31, in run
    local_file=pofile, filters='not_fuzzy')
  File "/home/discord/.local/lib/python3.6/site-packages/poeditor/client.py", line 442, in export
    "filters - filter results by {}".format(self.FILTER_BY))
poeditor.client.POEditorArgsException

```

**Comment by bakert** [comment]
I don't repro this on local because of

```
[2018-10-09 14:17:40,039] WARNING in logger: Missing poeditor.com API key
```

but I'm worried this is blocking actual needed jobs on prod?

I don't want to copy the key local and run it in case it screws something up.
