### ISSUE TITLE
Something to investigate maybe

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5766]
```
>>> from decksite.data import match as ms
>>> from shared import dtutil
>>> ms.insert_match(dtutil.now(), 28744, 0, 28745, 2, None, None, None)
Before BEGIN ([])
After BEGIN (['insert_match'])
Before COMMIT ([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/discord/decksite/decksite/data/match.py", line 36, in insert_match
    db().commit('insert_match')
  File "/home/discord/decksite/shared/database.py", line 103, in commit
    committed = self.open_transactions.pop()
IndexError: pop from empty list
```

**Comment by bakert** [comment]
I was adding a match manually and this happened which feels wrong.

**Comment by bakert** [comment]
This is because I'm not in app context so I have nowhere to store my ongoing transactions rather than a bug that affects prod. 

```
def db() -> Database:
    if has_request_context():
        ctx = request
    elif g:
        ctx = g
    else:
        ctx = Container() # Fallback context for testing.
    if not hasattr(ctx, 'database'):
        ctx.database = get_database(configuration.get_str('decksite_database'))
    return ctx.database
```

It also happens post-COMMIT so the INSERTs were run fine.
