### ISSUE TITLE
Gatherling scraper dies with exception

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5841]
```
...
Fetching https://gatherling.com/deck.php?mode=view&id=63996 (cache ok)
Traceback (most recent call last):
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 255, in lookup
    return decks_by_identifier[gatherling_id]
KeyError: '63990'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 120, in <module>
    run()
  File "run.py", line 34, in run
    task(sys.argv)
  File "run.py", line 80, in task
    s.scrape() # type: ignore
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 29, in scrape
    i = tournament(url, name)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 57, in tournament
    n = add_decks(dt, competition_id, final, s)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 100, in add_decks
    add_ids(matches, ds)
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 260, in add_ids
    m['right_id'] = lookup(m['right_identifier']).id if m['right_identifier'] else None
  File "/home/discord/decksite/decksite/scrapers/gatherling.py", line 257, in lookup
    raise InvalidDataException("Unable to find deck with gatherling id '{0}'".format(gatherling_id))
shared.pd_exception.InvalidDataException: Unable to find deck with gatherling id '63990'

```

**Comment by bakert** [comment]
This is the sane-seeming https://gatherling.com/deck.php?mode=view&id=63990 so I guess we have a partial tournament scrape as seen in #5024 and #4498 even though that's theoretically impossible as tournaments are only scraped when completed inside one horking great transaction these days.

**Comment by bakert** [comment]
Applying the fix from #5024 would mean doing this:

```
DELETE FROM `match` WHERE id IN (SELECT match_id FROM deck_match WHERE deck_id IN (SELECT id FROM deck WHERE competition_id IN (SELECT competition_id FROM deck WHERE identifier = '63990')));
DELETE FROM deck WHERE competition_id IN (SELECT competition_id FROM deck WHERE identifier = '63990');
```

and re-running the scraper.

But looking at

https://pennydreadfulmagic.com/competitions/727/

and 

https://gatherling.com/event.php?name=APAC%20Penny%20Dreadful%20Sundays%2010.07&view=standings

I don't see why we're even trying to add do anything to this tournament. We seem to have all the decks and all the matches.

**Comment by bakert** [comment]
Something makes us think we need to scrape this deck even though we already have it.

![image](https://user-images.githubusercontent.com/1541/48856285-dfb07580-ed6a-11e8-9937-d7de15a20379.png)

**Comment by bakert** [comment]
ok it's in the database with gatherling identifier of 63995 but on gatherling.com it has identifier 63996. That's an explanation as to why we see the behavior we do. But how it got in that state is perplexing.

**Comment by bakert** [comment]
https://gatherling.com/deck.php?mode=view&id=63995 says: "You do not have permission to view this deck. Decks are anonymous for privacy until event is finalized."

```
    gatherling_id = urllib.parse.parse_qs(urllib.parse.urlparse(str(d['url'])).query)['id'][0]
    d['identifier'] = gatherling_id
```

It's hard to see this as a bug and not a change on the Gatherling side post-first-scrape. But that also seems kind of unlikely.

I've updated the identifier in the prod db. 

```
MariaDB [decksite]> UPDATE deck SET identifier = '63996' WHERE identifier = '63995';
Query OK, 1 row affected (0.04 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

Closing.
