### ISSUE TITLE
500 error at /signup/ (duplicate key)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5890]
```
Failed to execute INSERT INTO deck ( created_date, updated_date, person_id, source_id, url, identifier, name, competition_id, archetype_id, resource_uri, featured_card, score, thumbnail_url, small_thumbnail_url, finish, reviewed ) VALUES ( IFNULL(%s, UNIX_TIMESTAMP()), UNIX_TIMESTAMP(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, FALSE ) with [1544654285.799203, 3001, 3, 'https://pennydreadfulmagic.com/competitions/736/', '["linkxness", 736, "1544654285"]', 'Curses', 736, None, None, None, None, None, None, None] because of (1062, 'Duplicate entry \'3-["linkxness", 736, "1544654285"]\' for key \'deck_source_id_identifier\'')

Reported on decksite by linkxness

            --------------------------------------------------------------------------------
            Request Method: POST
            Path: /signup/?
            Cookies: {'__cfduid': 'd1d6b21b2aca70c38f23b3b67356ac6441542752441', 'deck_id': '29666', '_gat_gtag_UA_109131120_1': '1', '_ga': 'GA1.2.900647789.1542752443', '_gid': 'GA1.2.799776205.1544654167', 'session': '.eJx9UctOwzAQ_BefI-TaefZWWgqFvgQSoCAUmWSTmDh2ZTtVo6r_jlOp9IDEcWbWszvjI8p2oFsmQVo0troDD7Gi5RKNSyaMQwW0vFXFFXOTK11k3FGIxD4JsB8mYezj2I9ohDz0jyKzquOiuGwSqqqgGC4wSp4dKcYjD7W2UllnQEvWgjMTXDYHCcY4D8U6W5PMWGYHKZofNulLSPf7nM3St-jw8Lwt7lfzkr9ubHOdt6oBF-qIWJ47owtGq_5uvYwtXi-mpPzqczLZb2scLGlV003q3sNhxzWYjLl-RoFPaZBQP74hAcFJQq_6UFmI_RhjD2koHVX_Lpl0Ky2T8mnaq8fv5l0sIKWzCoQhMzkfQrlKdy7Nh-vOfQQve8edmzLo00Nnm8z2wwi6BaZBo5OH_tRmma7AnSk7IU4__qWYlQ.DvMfRA.g_9bgnQU2CgQ7C9tWtvBr4oMsqg'}
            Endpoint: add_signup
            View Args: {}
            Person: 284250469684084737
            Referrer: https://pennydreadfulmagic.com/signup/
            Request Data: {'mtgo_username': 'linkxness', 'name': 'Curses', 'decklist': "3 Bile Blight\r\n2 Consuming Vapors\r\n1 Cruel Reality\r\n4 Curse of Death's Hold\r\n4 Curse of Misfortunes\r\n4 Curse of Thirst\r\n4 Distress\r\n3 Lake of the Dead\r\n1 Murderous Cut\r\n4 Read the Bones\r\n2 Sever the Bloodline\r\n2 Sunset Pyramid\r\n22 Swamp\r\n2 Vendetta\r\n2 Wretched Banquet\r\n\r\nSideboard:\r\n1 Bile Blight\r\n2 Consume the Meek\r\n1 Curse of Oblivion\r\n2 Desecration Demon\r\n3 Memoricide\r\n1 Moment of Craving\r\n2 Transgress the Mind\r\n2 Underworld Dreams\r\n1 Vendetta"}
Host: pennydreadfulmagic.com
Accept-Encoding: gzip
Cf-Ipcountry: DE
X-Forwarded-For: 31.18.252.149, 198.41.242.48
Cf-Ray: 4883ade17b71c4dd-DUS
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
Cache-Control: max-age=0
Origin: https://pennydreadfulmagic.com
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2950.1 Iron Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: https://pennydreadfulmagic.com/signup/
Accept-Language: en-US,en;q=0.8
Cookie: __cfduid=d1d6b21b2aca70c38f23b3b67356ac6441542752441; deck_id=29666; _gat_gtag_UA_109131120_1=1; _ga=GA1.2.900647789.1542752443; _gid=GA1.2.799776205.1544654167; session=.eJx9UctOwzAQ_BefI-TaefZWWgqFvgQSoCAUmWSTmDh2ZTtVo6r_jlOp9IDEcWbWszvjI8p2oFsmQVo0troDD7Gi5RKNSyaMQwW0vFXFFXOTK11k3FGIxD4JsB8mYezj2I9ohDz0jyKzquOiuGwSqqqgGC4wSp4dKcYjD7W2UllnQEvWgjMTXDYHCcY4D8U6W5PMWGYHKZofNulLSPf7nM3St-jw8Lwt7lfzkr9ubHOdt6oBF-qIWJ47owtGq_5uvYwtXi-mpPzqczLZb2scLGlV003q3sNhxzWYjLl-RoFPaZBQP74hAcFJQq_6UFmI_RhjD2koHVX_Lpl0Ky2T8mnaq8fv5l0sIKWzCoQhMzkfQrlKdy7Nh-vOfQQve8edmzLo00Nnm8z2wwi6BaZBo5OH_tRmma7AnSk7IU4__qWYlQ.DvMfRA.g_9bgnQU2CgQ7C9tWtvBr4oMsqg
Cf-Connecting-Ip: 31.18.252.149
X-Forwarded-Host: pennydreadfulmagic.com
X-Forwarded-Server: pennydreadfulmagic.com
Connection: Keep-Alive
Content-Length: 599
DatabaseException
Failed to execute INSERT INTO deck ( created_date, updated_date, person_id, source_id, url, identifier, name, competition_id, archetype_id, resource_uri, featured_card, score, thumbnail_url, small_thumbnail_url, finish, reviewed ) VALUES ( IFNULL(%s, UNIX_TIMESTAMP()), UNIX_TIMESTAMP(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, FALSE ) with [1544654285.799203, 3001, 3, 'https://pennydreadfulmagic.com/competitions/736/', '["linkxness", 736, "1544654285"]', 'Curses', 736, None, None, None, None, None, None, None] because of (1062, 'Duplicate entry \'3-["linkxness", 736, "1544654285"]\' for key \'deck_source_id_identifier\'')
Stack Trace:

  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./decksite/cache.py", line 79, in decorated_function
    response = make_response(f(*args, **kwargs))
  File "./decksite/main.py", line 307, in add_signup
    d = lg.signup(form)
  File "./decksite/league.py", line 180, in signup
    return deck.add_deck(form)
  File "./decksite/data/deck.py", line 355, in add_deck
    deck_id = db().insert(sql, values)
  File "./shared/database.py", line 89, in insert
    self.execute(sql, args)
  File "./shared/database.py", line 45, in execute
    [n, _] = self.execute_anything(sql, args, False)
  File "./shared/database.py", line 60, in execute_anything
    raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e))

Exception_hash: abd5035a2e939f10790d2e2212f27be4c067d906
```

**Comment by bakert** [comment]
Closing as a one off but interesting.

**Comment by bakert** [comment]
```
May 18 00:19:26 katelyngigante uwsgi[23132]: [2020-05-18 00:19:26,690] ERROR in app: Exception on /signup/ [POST]
May 18 00:19:26 katelyngigante uwsgi[23132]: Traceback (most recent call last):
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./shared/database.py", line 51, in execute_anything
May 18 00:19:26 katelyngigante uwsgi[23132]:     return self.execute_with_reconnect(sql, args, fetch_rows)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./shared/database.py", line 67, in execute_with_reconnect
May 18 00:19:26 katelyngigante uwsgi[23132]:     n = self.cursor.execute(sql, args)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
May 18 00:19:26 katelyngigante uwsgi[23132]:     res = self._query(query)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
May 18 00:19:26 katelyngigante uwsgi[23132]:     db.query(q)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
May 18 00:19:26 katelyngigante uwsgi[23132]:     _mysql.connection.query(self, query)
May 18 00:19:26 katelyngigante uwsgi[23132]: MySQLdb._exceptions.IntegrityError: (1062, 'Duplicate entry \'3-["thisguyagain365", 3191, "1589725140"]\' for key \'deck_source_id_identifier\'')
May 18 00:19:26 katelyngigante uwsgi[23132]: During handling of the above exception, another exception occurred:
May 18 00:19:26 katelyngigante uwsgi[23132]: Traceback (most recent call last):
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
May 18 00:19:26 katelyngigante uwsgi[23132]:     response = self.full_dispatch_request()
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
May 18 00:19:26 katelyngigante uwsgi[23132]:     rv = self.handle_user_exception(e)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
May 18 00:19:26 katelyngigante uwsgi[23132]:     reraise(exc_type, exc_value, tb)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
May 18 00:19:26 katelyngigante uwsgi[23132]:     raise value
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
May 18 00:19:26 katelyngigante uwsgi[23132]:     rv = self.dispatch_request()
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
May 18 00:19:26 katelyngigante uwsgi[23132]:     return self.view_functions[rule.endpoint](**req.view_args)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./decksite/cache.py", line 80, in decorated_function
May 18 00:19:26 katelyngigante uwsgi[23132]:     response = make_response(f(*args, **kwargs))
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./decksite/controllers/league.py", line 44, in add_signup
May 18 00:19:26 katelyngigante uwsgi[23132]:     d = lg.signup(form)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./decksite/league.py", line 186, in signup
May 18 00:19:26 katelyngigante uwsgi[23132]:     return deck.add_deck(form)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./decksite/data/deck.py", line 383, in add_deck
May 18 00:19:26 katelyngigante uwsgi[23132]:     deck_id = db().insert(sql, values)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./shared/database.py", line 88, in insert
May 18 00:19:26 katelyngigante uwsgi[23132]:     self.execute(sql, args)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./shared/database.py", line 44, in execute
May 18 00:19:26 katelyngigante uwsgi[23132]:     [n, _] = self.execute_anything(sql, args, False)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "./shared/database.py", line 59, in execute_anything
May 18 00:19:26 katelyngigante uwsgi[23132]:     raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e))
May 18 00:19:26 katelyngigante uwsgi[23132]: shared.pd_exception.DatabaseException: Failed to execute `INSERT INTO deck (
May 18 00:19:26 katelyngigante uwsgi[23132]:         created_date,
May 18 00:19:26 katelyngigante uwsgi[23132]:         updated_date,
May 18 00:19:26 katelyngigante uwsgi[23132]:         person_id,
May 18 00:19:26 katelyngigante uwsgi[23132]:         source_id,
May 18 00:19:26 katelyngigante uwsgi[23132]:         url,
May 18 00:19:26 katelyngigante uwsgi[23132]:         identifier,
May 18 00:19:26 katelyngigante uwsgi[23132]:         name,
May 18 00:19:26 katelyngigante uwsgi[23132]:         competition_id,
May 18 00:19:26 katelyngigante uwsgi[23132]:         archetype_id,
May 18 00:19:26 katelyngigante uwsgi[23132]:         resource_uri,
May 18 00:19:26 katelyngigante uwsgi[23132]:         featured_card,
May 18 00:19:26 katelyngigante uwsgi[23132]:         score,
May 18 00:19:26 katelyngigante uwsgi[23132]:         thumbnail_url,
May 18 00:19:26 katelyngigante uwsgi[23132]:         small_thumbnail_url,
May 18 00:19:26 katelyngigante uwsgi[23132]:         finish,
May 18 00:19:26 katelyngigante uwsgi[23132]:         decklist_hash,
May 18 00:19:26 katelyngigante uwsgi[23132]:         reviewed
May 18 00:19:26 katelyngigante uwsgi[23132]:     ) VALUES (
May 18 00:19:26 katelyngigante uwsgi[23132]:          IFNULL(%s, UNIX_TIMESTAMP()), UNIX_TIMESTAMP(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, FALSE
May 18 00:19:26 katelyngigante uwsgi[23132]:     )` with `[1589725140.304675, 4392, 3, 'https://pennydreadfulmagic.com/competitions/3191/', '["thisguyagain365", 3191, "1589725140"]', 'Ramp', 3191, None, None, None, None, None, None, None, '2b9705dc7bb99d0dfeba6bf5905883fc98910edb']` because of `(1062, 'Duplicate entry \'3-["thisguyagain365", 3191, "1589725140"]\' for key \'deck_source_id_identifier\'')`
May 18 00:19:26 katelyngigante uwsgi[23132]: [2020-05-18 00:19:26,756] ERROR in logger: At request path: /signup/
May 18 00:19:26 katelyngigante uwsgi[23132]: werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
May 18 00:19:26 katelyngigante uwsgi[23132]: 500 error at /signup/
May 18 00:19:26 katelyngigante uwsgi[23132]:  500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
May 18 00:19:26 katelyngigante uwsgi[23132]: Reported on decksite by thisguyagain365
May 18 00:19:26 katelyngigante uwsgi[23132]: <details><summary>
May 18 00:19:26 katelyngigante uwsgi[23132]: InternalServerError
May 18 00:19:26 katelyngigante uwsgi[23132]: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
May 18 00:19:26 katelyngigante uwsgi[23132]: </summary>
May 18 00:19:26 katelyngigante uwsgi[23132]: Stack Trace:
May 18 00:19:26 katelyngigante uwsgi[23132]: ```
May 18 00:19:26 katelyngigante uwsgi[23132]: Python traceback
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
May 18 00:19:26 katelyngigante uwsgi[23132]:     return self.wsgi_app(environ, start_response)
May 18 00:19:26 katelyngigante uwsgi[23132]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
May 18 00:19:26 katelyngigante uwsgi[23132]:     response = self.handle_exception(e)
May 18 00:19:26 katelyngigante uwsgi[23132]: ```
May 18 00:19:26 katelyngigante uwsgi[23132]: </details>
May 18 00:19:26 katelyngigante uwsgi[23132]: Exception_hash: f6dd8402d1e448b6b5c43b94364ed2c834629e77
May 18 00:19:26 katelyngigante uwsgi[23132]: <details><summary><strong>Request Data</strong></summary>
May 18 00:19:26 katelyngigante uwsgi[23132]: ```
May 18 00:19:26 katelyngigante uwsgi[23132]: Request Method: POST
May 18 00:19:26 katelyngigante uwsgi[23132]: Path: /signup/?
May 18 00:19:26 katelyngigante uwsgi[23132]: Cookies: ImmutableMultiDict([('__cfduid', 'd69987a321454c0a2530c22ee273f54f01589598043'), ('_ga', 'GA1.2.2116618994.1589598045'), ('_gid', 'GA1.2.2067445854.1589598045'), ('page_size', '20'), ('deck_id', '76467'), ('_gat_gtag_UA_109131120_1', '1'), ('session', '.eJx1UctOwzAQ_BefQ-UmcdJwaymCIp4qzyIUufHGMU3syHagEeLf2VaiOSBunt3ZnZ3xF8lbsA3XoD059raDgHDRKE2OS147RAIa1RgxYOUKY0WusERSOs7SMMriiCWMJmkck4FRm4LXgCzQRw9LbPw_onQuO1UPKrWREsTuNmf0XiuOsjAgjZcm7xxYzZvdal8pJ7ueS650lDBcZXjnqzB3nvsdYVbfzEJ9xhaqlOvN_GW-fClgfXFdyTv1VAx8bzaApr8ILwpw7hcTvr06aberxaW6X5yv2eb-0QnR2KT8NNHnFOdh2yoLLueY35hlNKRhxtgooxGbTKKhv4s0ofGE0oBYKLFUHUR8sVyWt-NnUVLB6OVkVW6vpn3xcafjtD9FEQy0RTevGCF-lCp7rO0Dc4fH6N2gxFtA9ktz37d7-8AtWPIdkD9Rem4l4NG6q-vvH-hRqLE.XsFHug.FM-DPy-mIZntDY_DOsdtLvxC7h4')])
May 18 00:19:26 katelyngigante uwsgi[23132]: Endpoint: add_signup
May 18 00:19:26 katelyngigante uwsgi[23132]: View Args: {}
May 18 00:19:26 katelyngigante uwsgi[23132]: Person: 701972394356506744
May 18 00:19:26 katelyngigante uwsgi[23132]: Referrer: https://pennydreadfulmagic.com/signup/
May 18 00:19:26 katelyngigante uwsgi[23132]: Request Data: {'mtgo_username': 'ThisGuyAgain365', 'name': 'Ramp', 'decklist': '<?xml version="1.0" encoding="utf-8"?>\r\n<Deck xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\r\n  <NetDeckID>0</NetDeckID>\r\n  <PreconstructedDeckID>0</PreconstructedDeckID>\r\n  <Cards CatID="37598" Quantity="4" Sideboard="false" Name="Birds of Paradise" />\r\n  <Cards CatID="53106" Quantity="1" Sideboard="false" Name="Fyndhorn Elves" />\r\n  <Cards CatID="53105" Quantity="3" Sideboard="false" Name="Fyndhorn Elves" />\r\n  <Cards CatID="41605" Quantity="4" Sideboard="false" Name="Llanowar Elves" />\r\n  <Cards CatID="52815" Quantity="4" Sideboard="false" Name="Rofellos, Llanowar Emissary" />\r\n  <Cards CatID="72712" Quantity="4" Sideboard="false" Name="Llanowar Tribe" />\r\n  <Cards CatID="57170" Quantity="4" Sideboard="false" Name="Wolfbriar Elemental" />\r\n  <Cards CatID="72694" Quantity="4" Sideboard="false" Name="Deep Forest Hermit" />\r\n  <Cards CatID="78438" Quantity="4" Sideboard="false" Name="Feasting Troll King" />\r\n  <Cards CatID="55996" Quantity="2" Sideboard="false" Name="Foe-Razer Regent" />\r\n  <Cards CatID="36178" Quantity="1" Sideboard="false" Name="Garruk Wildspeaker" />\r\n  <Cards CatID="52741" Quantity="3" Sideboard="false" Name="Nature\'s Lore" />\r\n  <Cards CatID="79632" Quantity="22" Sideboard="false" Name="Forest" />\r\n  <Cards CatID="71516" Quantity="2" Sideboard="true" Name="Scrabbling Claws" />\r\n  <Cards CatID="79518" Quantity="3" Sideboard="true" Name="Return to Nature" />\r\n  <Cards CatID="65005" Quantity="2" Sideboard="true" Name="Nissa, Worldwaker" />\r\n  <Cards CatID="68545" Quantity="2" Sideboard="true" Name="Pelakka Wurm" />\r\n  <Cards CatID="41413" Quantity="3" Sideboard="true" Name="Dungrove Elder" />\r\n  <Cards CatID="18790" Quantity="3" Sideboard="true" Name="Stabilizer" />\r\n</Deck>'}
May 18 00:19:26 katelyngigante uwsgi[23132]: Host: pennydreadfulmagic.com
May 18 00:19:26 katelyngigante uwsgi[23132]: Accept-Encoding: gzip
May 18 00:19:26 katelyngigante uwsgi[23132]: Cf-Ipcountry: US
May 18 00:19:26 katelyngigante uwsgi[23132]: X-Forwarded-For: 2605:6000:1526:d083:15cf:f808:8398:1bfb, 172.69.22.46
May 18 00:19:26 katelyngigante uwsgi[23132]: Cf-Ray: 594df88d9acf9b18-SJC
May 18 00:19:26 katelyngigante uwsgi[23132]: X-Forwarded-Proto: https
May 18 00:19:26 katelyngigante uwsgi[23132]: Cf-Visitor: {"scheme":"https"}
May 18 00:19:26 katelyngigante uwsgi[23132]: Cache-Control: max-age=0
May 18 00:19:26 katelyngigante uwsgi[23132]: Upgrade-Insecure-Requests: 1
May 18 00:19:26 katelyngigante uwsgi[23132]: Origin: https://pennydreadfulmagic.com
May 18 00:19:26 katelyngigante uwsgi[23132]: Content-Type: application/x-www-form-urlencoded
May 18 00:19:26 katelyngigante uwsgi[23132]: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
May 18 00:19:26 katelyngigante uwsgi[23132]: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
May 18 00:19:26 katelyngigante uwsgi[23132]: Sec-Fetch-Site: same-origin
May 18 00:19:26 katelyngigante uwsgi[23132]: Sec-Fetch-Mode: navigate
May 18 00:19:26 katelyngigante uwsgi[23132]: Sec-Fetch-User: ?1
May 18 00:19:26 katelyngigante uwsgi[23132]: Sec-Fetch-Dest: document
May 18 00:19:26 katelyngigante uwsgi[23132]: Referer: https://pennydreadfulmagic.com/signup/
May 18 00:19:26 katelyngigante uwsgi[23132]: Accept-Language: en-US,en;q=0.9
May 18 00:19:26 katelyngigante uwsgi[23132]: Cookie: __cfduid=d69987a321454c0a2530c22ee273f54f01589598043; _ga=GA1.2.2116618994.1589598045; _gid=GA1.2.2067445854.1589598045; page_size=20; deck_id=76467; _gat_gtag_UA_109131120_1=1; session=.eJx1UctOwzAQ_BefQ-UmcdJwaymCIp4qzyIUufHGMU3syHagEeLf2VaiOSBunt3ZnZ3xF8lbsA3XoD059raDgHDRKE2OS147RAIa1RgxYOUKY0WusERSOs7SMMriiCWMJmkck4FRm4LXgCzQRw9LbPw_onQuO1UPKrWREsTuNmf0XiuOsjAgjZcm7xxYzZvdal8pJ7ueS650lDBcZXjnqzB3nvsdYVbfzEJ9xhaqlOvN_GW-fClgfXFdyTv1VAx8bzaApr8ILwpw7hcTvr06aberxaW6X5yv2eb-0QnR2KT8NNHnFOdh2yoLLueY35hlNKRhxtgooxGbTKKhv4s0ofGE0oBYKLFUHUR8sVyWt-NnUVLB6OVkVW6vpn3xcafjtD9FEQy0RTevGCF-lCp7rO0Dc4fH6N2gxFtA9ktz37d7-8AtWPIdkD9Rem4l4NG6q-vvH-hRqLE.XsFHug.FM-DPy-mIZntDY_DOsdtLvxC7h4
May 18 00:19:26 katelyngigante uwsgi[23132]: Cf-Request-Id: 02c499ac7f00009b18faa94200000001
May 18 00:19:26 katelyngigante uwsgi[23132]: Cf-Connecting-Ip: 2605:6000:1526:d083:15cf:f808:8398:1bfb
May 18 00:19:26 katelyngigante uwsgi[23132]: Cdn-Loop: cloudflare
May 18 00:19:26 katelyngigante uwsgi[23132]: X-Forwarded-Host: pennydreadfulmagic.com
May 18 00:19:26 katelyngigante uwsgi[23132]: X-Forwarded-Server: pennydreadfulmagic.com
May 18 00:19:26 katelyngigante uwsgi[23132]: Content-Length: 2578
May 18 00:19:26 katelyngigante uwsgi[23132]: Connection: Keep-Alive
May 18 00:19:26 katelyngigante uwsgi[23132]: ```
May 18 00:19:26 katelyngigante uwsgi[23132]: </details>
```

**Comment by bakert** [comment]
It happened again 18 months later. Hm.
