### ISSUE TITLE
Unrecognized locales cause 500s

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#6153]
For example: `/cards/Electrostatic%20Field/?locale=NA`

 - [ ] Do NOT use querystring for locale, it causes search results to be stored in Google than then switch the locale of the viewer.
 - [ ] Send a Bad Request not an Internal Server Error if you ask to be switched to a locale that does not exist.

**Comment by bakert** [comment]
It's not obvious to me where the right place to catch this is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bakert/pd/decksite/cache.py", line 79, in decorated_function
    response = make_response(f(*args, **kwargs))
  File "/Users/bakert/pd/decksite/main.py", line 45, in home
    view = Home(ns.all_news(max_items=10), ds.latest_decks(), cs.load_cards(season_id=get_season_id()), ms.stats())
  File "/Users/bakert/pd/decksite/views/home.py", line 16, in __init__
    self.setup_decks(decks)
  File "/Users/bakert/pd/decksite/views/home.py", line 48, in setup_decks
    'title': gettext('Recent Top League Decks'),
  File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 227, in get_translations
    [get_locale()],
  File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 261, in get_locale
    locale = Locale.parse(rv)
  File "/usr/local/lib/python3.7/site-packages/babel/core.py", line 331, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'na'
```

It's possible we want to do more explicit checking in `localization.py` where we do `check_sql_injection`?
