### ISSUE TITLE
We don't create the `fetcher` table when you run discordbot for the first time.

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#661]
We should either include in SETUP or perform automatically.

**Comment by bakert** [comment]
This is not true. Closing.

**Comment by bakert** [comment]
Problem here seems to be that version in db_version table is updated before db setup completes successfully. So on subsequent runs stuff may not have been done but db_version() < SCHEMA_VERSION is false.

[deepthought pd] python run.py discordbot
**************** database.py stuff happening
0
0
66
******* SETUPPPPPPP
/Users/bakert/pd/shared/database_mysql.py:36: Warning: (1050, "Table 'db_version' already exists")
  self.cursor.execute(sql, args)
/Users/bakert/pd/shared/database_mysql.py:36: Warning: (1050, "Table 'version' already exists")
  self.cursor.execute(sql, args)
/Users/bakert/pd/shared/database_mysql.py:36: Warning: (1050, "Table 'card' already exists")
  self.cursor.execute(sql, args)
/Users/bakert/pd/shared/database_mysql.py:36: Warning: (1050, "Table 'face' already exists")
  self.cursor.execute(sql, args)
Traceback (most recent call last):
  File "/Users/bakert/pd/shared/database_mysql.py", line 36, in execute
    self.cursor.execute(sql, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/connections.py", line 270, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRAGMA writable_schema = 1' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bakert/pd/magic/database.py", line 21, in init
    delete()
  File "/Users/bakert/pd/magic/database.py", line 128, in delete
    db().execute("PRAGMA writable_schema = 1")
  File "/Users/bakert/pd/shared/database_mysql.py", line 39, in execute
    raise DatabaseException('Failed to execute `{sql}` with args `{args}` because of `{e}`'.format(sql=sql, args=args, e=e)) from e
shared.pd_exception.DatabaseException: Failed to execute `PRAGMA writable_schema = 1` with args `[]` because of `(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRAGMA writable_schema = 1' at line 1")`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bakert/pd/shared/database_mysql.py", line 36, in execute
    self.cursor.execute(sql, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MySQLdb/connections.py", line 270, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1170, "BLOB/TEXT column 'name' used in key specification without a key length")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 54, in <module>
    run()
  File "run.py", line 11, in run
    from discordbot import bot
  File "/Users/bakert/pd/discordbot/bot.py", line 3, in <module>
    from discordbot import command, emoji
  File "/Users/bakert/pd/discordbot/command.py", line 11, in <module>
    from discordbot import emoji
  File "/Users/bakert/pd/discordbot/emoji.py", line 3, in <module>
    from magic import oracle
  File "/Users/bakert/pd/magic/oracle.py", line 1, in <module>
    from magic import card, fetcher, mana, multiverse
  File "/Users/bakert/pd/magic/fetcher.py", line 8, in <module>
    import magic.fetcher_internal as internal
  File "/Users/bakert/pd/magic/fetcher_internal.py", line 10, in <module>
    from magic import database
  File "/Users/bakert/pd/magic/database.py", line 154, in <module>
    init()
  File "/Users/bakert/pd/magic/database.py", line 24, in init
    setup()
  File "/Users/bakert/pd/magic/database.py", line 42, in setup
    db().execute(sql)
  File "/Users/bakert/pd/shared/database_mysql.py", line 39, in execute
    raise DatabaseException('Failed to execute `{sql}` with args `{args}` because of `{e}`'.format(sql=sql, args=args, e=e)) from e
shared.pd_exception.DatabaseException: Failed to execute `CREATE TABLE IF NOT EXISTS `set` (`name` TEXT  NOT NULL UNIQUE , `border` TEXT  NOT NULL  , `release_date` INTEGER  NOT NULL  , `magiccardsinfo_code` TEXT   UNIQUE , `type` TEXT  NOT NULL  , `id` INTEGER PRIMARY KEY NOT NULL  , `online_only` INTEGER    , `gatherer_code` TEXT   UNIQUE , `old_code` TEXT   UNIQUE , `code` TEXT  NOT NULL UNIQUE )` with args `[]` because of `(1170, "BLOB/TEXT column 'name' used in key specification without a key length")`
[deepthought pd] mysql pd_magic
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 34
Server version: 5.6.34 Source distribution

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT version FROM db_version;
+---------+
| version |
+---------+
|      66 |
+---------+
1 row in set (0.00 sec)

mysql> ^DBye
[deepthought pd]

**Comment by bakert** [comment]
We're not using MySQL for this stuff yet. Use ".sqlite" in the name of your magic_database in your config.json to avoid this problem and continue using SQLite for cards db.
