### ISSUE TITLE
tappedout scraper is failing

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#6789]
```
Error running task ['run.py', 'scraper', 'all']

Reported on CLI by CLI

FetchException Expecting value: line 1 column 1 (char 0)
Stack Trace:


Python traceback

  File "run.py", line 128, in <module>
    run()
  File "run.py", line 70, in task
    run_all_tasks(module)
  File "run.py", line 115, in run_all_tasks
    s.scrape() # type: ignore
  File "/home/discord/decksite/decksite/scrapers/tappedout.py", line 19, in scrape
    raw_decks = fetch_decks()
  File "/home/discord/decksite/decksite/scrapers/tappedout.py", line 34, in fetch_decks
    return fetch_tools.fetch_json('https://tappedout.net/api/deck/latest/penny-dreadful/')
  File "/home/discord/decksite/shared/fetch_tools.py", line 62, in fetch_json
    raise FetchException(e)


Exception_hash: 074e3c678888dde74db3e67df051fb5112daa781

Labels: CLI; FetchException
```

**Comment by bakert** [comment]
Runs to completion on local for me.

**Comment by bakert** [comment]
We are getting a 403 Forbidden on prod.

```
Fetching https://api.scryfall.com/bulk-data (cache ok)
[2019-11-11 19:20:32,947] WARNING in logger: Logged in to TappedOut: False
Fetching https://tappedout.net/api/deck/latest/penny-dreadful/ (cache ok)
Failed to load JSON:
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

Error running task ['run.py', 'scraper', 'tappedout']
Reported on CLI by CLI

<details><summary>
FetchException
Expecting value: line 1 column 1 (char 0)
</summary>

Stack Trace:

```

Python traceback

  File "run.py", line 128, in <module>
    run()
  File "run.py", line 82, in task
    exitcode = s.scrape() # type: ignore
  File "/home/discord/decksite/decksite/scrapers/tappedout.py", line 19, in scrape
    raw_decks = fetch_decks()
  File "/home/discord/decksite/decksite/scrapers/tappedout.py", line 34, in fetch_decks
    return fetch_tools.fetch_json('https://tappedout.net/api/deck/latest/penny-dreadful/')
  File "/home/discord/decksite/shared/fetch_tools.py", line 62, in fetch_json
    raise FetchException(e)


```

</details>

Exception_hash: 2e23e5e3e0ad4476bdcce7858c09d84a04b34654

Traceback (most recent call last):
  File "/home/discord/decksite/shared/fetch_tools.py", line 58, in fetch_json
    return json.loads(blob)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 128, in <module>
    run()
  File "run.py", line 35, in run
    task(sys.argv)
  File "run.py", line 82, in task
    exitcode = s.scrape() # type: ignore
  File "/home/discord/decksite/decksite/scrapers/tappedout.py", line 19, in scrape
    raw_decks = fetch_decks()
  File "/home/discord/decksite/decksite/scrapers/tappedout.py", line 34, in fetch_decks
    return fetch_tools.fetch_json('https://tappedout.net/api/deck/latest/penny-dreadful/')
  File "/home/discord/decksite/shared/fetch_tools.py", line 62, in fetch_json
    raise FetchException(e)
shared.fetch_tools.FetchException: Expecting value: line 1 column 1 (char 0)
```

**Comment by bakert** [comment]
That page loads in a browser for me so I guess we are rate limited.

**Comment by bakert** [comment]
I turned the tappedout scraper off in 10dd2716. Let's give it a rest and see if we get unblocked.

**Comment by bakert** [comment]
Tried just now still 403.

**Comment by bakert** [comment]
Still Forbidden.

**Comment by bakert** [comment]
https://tappedout.net/api/deck/latest/penny-dreadful/

Works in my browser. 403 via wget from terminal, same as on prod.

So possibly we need to supply a User-Agent?

**Comment by bakert** [comment]
I think we're done with Tapped Out. They haven't had our proper legality for a long time.
