### ISSUE TITLE
500 error at /api/gitpull on logsite

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#7191]
```
 500 error at /api/gitpull

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Reported on logsite by logged_out

InternalServerError 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Stack Trace:


Python traceback

  File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)


Exception_hash: 15c4ac9d81725488a0e577b38f62ab01229a08cf

Request Data

Request Method: POST
Path: /api/gitpull?
Cookies: ImmutableMultiDict([])
Endpoint: process_github_webhook
View Args: {}
Person: logged_out
Referrer: None
Request Data: {}
Host: logs.pennydreadfulmagic.com
Accept-Encoding: gzip
Cf-Ipcountry: US
X-Forwarded-For: 140.82.115.245, 172.68.132.43
Cf-Ray: 5807b4d1d83cea1c-SJC
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
User-Agent: GitHub-Hookshot/47eb3c7
Accept: */*
X-Github-Delivery: e81cb906-792b-11ea-904f-2d312804ec65
X-Github-Event: push
Content-Type: application/json
Cf-Connecting-Ip: 140.82.115.245
Cdn-Loop: cloudflare
X-Forwarded-Host: logs.pennydreadfulmagic.com
X-Forwarded-Server: logs.pennydreadfulmagic.com
Connection: Keep-Alive
Content-Length: 10580
Labels: logsite; InternalServerError
```

**Comment by bakert** [comment]
Might be this?

```
Apr 08 10:00:25 katelyngigante uwsgi[620]: sh: webpack: command not found
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! Linux 5.3.11-x86_64-linode131
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! argv "/usr/bin/node6" "/usr/bin/npm-default" "run-script" "build"
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! node v6.14.3
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! npm  v3.10.10
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! file sh
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! code ELIFECYCLE
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! errno ENOENT
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! syscall spawn
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! penny-dreadful-tools@1.0.0 build: `webpack -p --progress --config decksite/webpack.config.js`
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! spawn ENOENT
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR!
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! Failed at the penny-dreadful-tools@1.0.0 build script 'webpack -p --progress --config decksite/webpack.config.js'.
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! Make sure you have the latest version of node.js and npm installed.
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! If you do, this is most likely a problem with the penny-dreadful-tools package,
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! not with npm itself.
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! Tell the author that this fails on your system:
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR!     webpack -p --progress --config decksite/webpack.config.js
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! You can get information on how to open an issue for this project with:
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR!     npm bugs penny-dreadful-tools
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! Or if that isn't available, you can get their info via:
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR!     npm owner ls penny-dreadful-tools
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! There is likely additional logging output above.
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR! Please include the following file with any support request:
Apr 08 10:00:25 katelyngigante uwsgi[620]: npm ERR!     /home/discord/logsite/npm-debug.log
Apr 08 10:00:25 katelyngigante uwsgi[620]: ...gracefully killing workers...
Apr 08 10:00:25 katelyngigante uwsgi[620]: Gracefully killing worker 1 (pid: 4901)...
```

**Comment by bakert** [comment]
Oh no. It's this:

```
Apr 08 10:00:24 katelyngigante uwsgi[620]: [2020-04-08 10:00:24,615] ERROR in app: Exception on /api/gitpull [POST]
Apr 08 10:00:24 katelyngigante uwsgi[620]: Traceback (most recent call last):
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
Apr 08 10:00:24 katelyngigante uwsgi[620]:     response = self.full_dispatch_request()
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
Apr 08 10:00:24 katelyngigante uwsgi[620]:     rv = self.handle_user_exception(e)
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
Apr 08 10:00:24 katelyngigante uwsgi[620]:     reraise(exc_type, exc_value, tb)
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Apr 08 10:00:24 katelyngigante uwsgi[620]:     raise value
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
Apr 08 10:00:24 katelyngigante uwsgi[620]:     rv = self.dispatch_request()
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
Apr 08 10:00:24 katelyngigante uwsgi[620]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "./shared_web/api.py", line 20, in process_github_webhook
Apr 08 10:00:24 katelyngigante uwsgi[620]:     subprocess.check_output(['git', 'fetch'])
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 411, in check_output
Apr 08 10:00:24 katelyngigante uwsgi[620]:     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
Apr 08 10:00:24 katelyngigante uwsgi[620]:   File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 512, in run
Apr 08 10:00:24 katelyngigante uwsgi[620]:     raise CalledProcessError(retcode, process.args,
Apr 08 10:00:24 katelyngigante uwsgi[620]: subprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 1.
Apr 08 10:00:24 katelyngigante uwsgi[620]: [2020-04-08 10:00:24,740] ERROR in logger: At request path: /api/gitpull
```

**Comment by bakert** [comment]
Meh.
