### ISSUE TITLE
500 error at /api/archetype/reassign

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#7234]
```
500 error at /api/archetype/reassign

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Reported on decksite by wizzerinus

InternalServerError 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Stack Trace:


Python traceback

  File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)


Exception_hash: f6dd8402d1e448b6b5c43b94364ed2c834629e77

Request Data

Request Method: POST
Path: /api/archetype/reassign?
Cookies: ImmutableMultiDict([('__cfduid', 'd824412b12e2f8fffd6eeeb194b7b5fd31586883513'), ('page_size', '20'), ('session', '.eJx1UdtqwkAQ_Zd9DpJorr4lFRtLUQpqwVLCkozJ6mbX7oV4wX_vRFAfSt92zjkzZ-bshRQHUC0VIAwZG2XBIbRqmSDjLeUaqwpa1srqTlZMl1JVBUOEeH7iBvHIj7wwStwo9l3yVHBZUg6oUhbR__VMFLVl_OHAZV1D1a-lpbj5jCJv5JDW1LKwGpSgbT-2Y-czKCasxiGSWtMMC22o6TnR5Iu3dRTPj4ouMm_fTYfJz3vgpc1mdj4-9UbuAU-9EFqWoPW9JjsvnQduCmphj9nCJmu3281WWZPuZhxa7IfjgSnQBcXUvCCO_CQKh_4gGuJN4ZPucwxdP3ZdhyjYItQ8PMrM77o4ni5fJ6G3D15Web5M8894wlcfmz4YjPGAx3xhdvg7bHtC7JaUfjwGO4kW3w65DS3MqW8gGVAFilwd8idEQ1UNuLOwnF9_ASXlo5E.Xpm8Uw.P9I9fHAHQeQ9yEBT-i-jPE06KdY')])
Endpoint: post_reassign
View Args: {}
Person: 149058347167907840
Referrer: https://pennydreadfulmagic.com/admin/rules/
Request Data: {'deck_id': '71591', 'archetype_id': '256'}
Host: pennydreadfulmagic.com
Accept-Encoding: gzip
Cf-Ipcountry: RU
X-Forwarded-For: 46.242.8.135, 172.69.22.130
Cf-Ray: 5856d0c8ad89736f-SJC
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Origin: https://pennydreadfulmagic.com
Dnt: 1
Referer: https://pennydreadfulmagic.com/admin/rules/
Cookie: __cfduid=d824412b12e2f8fffd6eeeb194b7b5fd31586883513; page_size=20; session=.eJx1UdtqwkAQ_Zd9DpJorr4lFRtLUQpqwVLCkozJ6mbX7oV4wX_vRFAfSt92zjkzZ-bshRQHUC0VIAwZG2XBIbRqmSDjLeUaqwpa1srqTlZMl1JVBUOEeH7iBvHIj7wwStwo9l3yVHBZUg6oUhbR__VMFLVl_OHAZV1D1a-lpbj5jCJv5JDW1LKwGpSgbT-2Y-czKCasxiGSWtMMC22o6TnR5Iu3dRTPj4ouMm_fTYfJz3vgpc1mdj4-9UbuAU-9EFqWoPW9JjsvnQduCmphj9nCJmu3281WWZPuZhxa7IfjgSnQBcXUvCCO_CQKh_4gGuJN4ZPucwxdP3ZdhyjYItQ8PMrM77o4ni5fJ6G3D15Web5M8894wlcfmz4YjPGAx3xhdvg7bHtC7JaUfjwGO4kW3w65DS3MqW8gGVAFilwd8idEQ1UNuLOwnF9_ASXlo5E.Xpm8Uw.P9I9fHAHQeQ9yEBT-i-jPE06KdY
Cf-Request-Id: 022a20d1640000736fe1337200000001
Cf-Connecting-Ip: 46.242.8.135
Cdn-Loop: cloudflare
X-Forwarded-Host: pennydreadfulmagic.com
X-Forwarded-Server: pennydreadfulmagic.com
Content-Length: 30
Connection: Keep-Alive
Labels: decksite; InternalServerError
```

**Comment by bakert** [comment]
```
Apr 18 00:48:44 katelyngigante uwsgi[21920]: [2020-04-18 00:48:44,454] ERROR in app: Exception on /api/archetype/reassign [POST]
Apr 18 00:48:44 katelyngigante uwsgi[21920]: Traceback (most recent call last):
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./shared/database.py", line 51, in execute_anything
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     return self.execute_with_reconnect(sql, args, fetch_rows)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./shared/database.py", line 81, in execute_with_reconnect
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     raise e
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./shared/database.py", line 67, in execute_with_reconnect
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     n = self.cursor.execute(sql, args)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     res = self._query(query)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     db.query(q)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     _mysql.connection.query(self, query)
Apr 18 00:48:44 katelyngigante uwsgi[21920]: MySQLdb._exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
Apr 18 00:48:44 katelyngigante uwsgi[21920]: During handling of the above exception, another exception occurred:
Apr 18 00:48:44 katelyngigante uwsgi[21920]: Traceback (most recent call last):
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     response = self.full_dispatch_request()
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     rv = self.handle_user_exception(e)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     reraise(exc_type, exc_value, tb)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     raise value
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     rv = self.dispatch_request()
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./decksite/auth.py", line 25, in decorated_function
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     return f(*args, **kwargs)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./shared_web/decorators.py", line 41, in wrapper
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     return f(*args, **kwargs)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./decksite/controllers/api.py", line 206, in post_reassign
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     archs.assign(deck_id, archetype_id, auth.person_id())
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./decksite/data/archetype.py", line 89, in assign
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     db().execute(f'UPDATE deck SET reviewed = %s, archetype_id = %s WHERE id = %s {and_clause}', [reviewed, archetype_id, deck_id])
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./shared/database.py", line 44, in execute
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     [n, _] = self.execute_anything(sql, args, False)
Apr 18 00:48:44 katelyngigante uwsgi[21920]:   File "./shared/database.py", line 59, in execute_anything
Apr 18 00:48:44 katelyngigante uwsgi[21920]:     raise DatabaseException('Failed to execute `{sql}` with `{args}` because of `{e}`'.format(sql=sql, args=args, e=e))
Apr 18 00:48:44 katelyngigante uwsgi[21920]: shared.pd_exception.DatabaseException: Failed to execute `UPDATE deck SET reviewed = %s, archetype_id = %s WHERE id = %s ` with `[True, '256', '71591']` beca>
Apr 18 00:48:44 katelyngigante uwsgi[21920]: [2020-04-18 00:48:44,824] ERROR in logger: At request path: /api/archetype/reassign
```

**Comment by bakert** [comment]
As this is a deadlock and a one-off I'm going to close this for now. Will reopen if it reoccurs.
