### ISSUE TITLE
500 at /cmc/charts/<specific chart>

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#7336]
```
May 12 04:30:58 katelyngigante uwsgi[1843]: [2020-05-12 04:30:58,251] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:58 katelyngigante uwsgi[1843]: [2020-05-12 04:30:58,251] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:58 katelyngigante uwsgi[1843]: [2020-05-12 04:30:58,538] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:58 katelyngigante uwsgi[1843]: [2020-05-12 04:30:58,538] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:58 katelyngigante uwsgi[1843]: [2020-05-12 04:30:58,834] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:58 katelyngigante uwsgi[1843]: [2020-05-12 04:30:58,835] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:59 katelyngigante uwsgi[1843]: [2020-05-12 04:30:59,103] WARNING in logger: Chart at /home/discord/decksite/images/charts/75698-cmc.png is suspiciously small.
May 12 04:30:59 katelyngigante uwsgi[1843]: [2020-05-12 04:30:59,103] ERROR in logger: Unable to generate cmc chart for 75698 in 3 attempts.
May 12 04:30:59 katelyngigante uwsgi[1843]: [2020-05-12 04:30:59,103] ERROR in app: Exception on /charts/cmc/75698-cmc.png [GET]
May 12 04:30:59 katelyngigante uwsgi[1843]: Traceback (most recent call last):
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
May 12 04:30:59 katelyngigante uwsgi[1843]:     response = self.full_dispatch_request()
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
May 12 04:30:59 katelyngigante uwsgi[1843]:     rv = self.handle_user_exception(e)
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
May 12 04:30:59 katelyngigante uwsgi[1843]:     reraise(exc_type, exc_value, tb)
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
May 12 04:30:59 katelyngigante uwsgi[1843]:     raise value
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
May 12 04:30:59 katelyngigante uwsgi[1843]:     rv = self.dispatch_request()
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
May 12 04:30:59 katelyngigante uwsgi[1843]:     return self.view_functions[rule.endpoint](**req.view_args)
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "./decksite/main.py", line 44, in cmc_chart
May 12 04:30:59 katelyngigante uwsgi[1843]:     return send_file(chart.cmc(int(deck_id)))
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "./decksite/charts/chart.py", line 42, in cmc
May 12 04:30:59 katelyngigante uwsgi[1843]:     return cmc(deck_id, attempts + 1)
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "./decksite/charts/chart.py", line 42, in cmc
May 12 04:30:59 katelyngigante uwsgi[1843]:     return cmc(deck_id, attempts + 1)
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "./decksite/charts/chart.py", line 42, in cmc
May 12 04:30:59 katelyngigante uwsgi[1843]:     return cmc(deck_id, attempts + 1)
May 12 04:30:59 katelyngigante uwsgi[1843]:   [Previous line repeated 1 more time]
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "./decksite/charts/chart.py", line 21, in cmc
May 12 04:30:59 katelyngigante uwsgi[1843]:     raise OperationalException(msg)
May 12 04:30:59 katelyngigante uwsgi[1843]: shared.pd_exception.OperationalException: Unable to generate cmc chart for 75698 in 3 attempts.
May 12 04:30:59 katelyngigante uwsgi[1843]: [2020-05-12 04:30:59,134] ERROR in logger: At request path: /charts/cmc/75698-cmc.png
May 12 04:30:59 katelyngigante uwsgi[1843]: werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
May 12 04:30:59 katelyngigante uwsgi[1843]: 500 error at /charts/cmc/75698-cmc.png
May 12 04:30:59 katelyngigante uwsgi[1843]:  500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
May 12 04:30:59 katelyngigante uwsgi[1843]: Reported on decksite by zachf
May 12 04:30:59 katelyngigante uwsgi[1843]: <details><summary>
May 12 04:30:59 katelyngigante uwsgi[1843]: InternalServerError
May 12 04:30:59 katelyngigante uwsgi[1843]: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
May 12 04:30:59 katelyngigante uwsgi[1843]: </summary>
May 12 04:30:59 katelyngigante uwsgi[1843]: Stack Trace:
May 12 04:30:59 katelyngigante uwsgi[1843]: ```
May 12 04:30:59 katelyngigante uwsgi[1843]: Python traceback
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
May 12 04:30:59 katelyngigante uwsgi[1843]:     return self.wsgi_app(environ, start_response)
May 12 04:30:59 katelyngigante uwsgi[1843]:   File "/home/discord/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
May 12 04:30:59 katelyngigante uwsgi[1843]:     response = self.handle_exception(e)
May 12 04:30:59 katelyngigante uwsgi[1843]: ```
May 12 04:30:59 katelyngigante uwsgi[1843]: </details>
May 12 04:30:59 katelyngigante uwsgi[1843]: Exception_hash: f6dd8402d1e448b6b5c43b94364ed2c834629e77
May 12 04:30:59 katelyngigante uwsgi[1843]: <details><summary><strong>Request Data</strong></summary>
May 12 04:30:59 katelyngigante uwsgi[1843]: ```
May 12 04:30:59 katelyngigante uwsgi[1843]: Request Method: GET
May 12 04:30:59 katelyngigante uwsgi[1843]: Path: /charts/cmc/75698-cmc.png?
May 12 04:30:59 katelyngigante uwsgi[1843]: Cookies: ImmutableMultiDict([('__cfduid', 'd2f9729cebf6ecae8cac1d9f7e22a9e2f1589221366'), ('_ga', 'GA1.2.1298548655.1589221369'), ('_gid', 'GA1.2.677192905.1589221369'), ('_gat_gtag_UA_109131120_1', '1'), ('deck_id', '75698'), ('session', '.eJx1UU1PwzAM_S85l6lNuy3djVEmEEJodLABQlXWpmlGk1RJCvvQ_jvupK0HxCWyn_387JcDyhpmJFVMOTRxpmUeooUUCk1KWlvICiaF1EWfC5trU2QCIDQiJMaYYHjjKI7xcIj6jlrntGbQxdTVSwqF_ylCZbwVdXFeodacs6JbzWp1kgqjmHhIOq6z1jKjqOwm72lelcDXtHUVzqyjroOTgszmq826xJFOlvN0MaaljPzlsglvX-77fqe_GFx6QDTPmbXnHD0-R_gu1Nw5O02fdIL5K1f7tVJjPH_zgc-2jTDMZhRMC4YkJngUkGAQEhJgHPb1zseRHxHf95BhJUDVRUQW8bd8x9dt3FarWfuTKv0gtklEbzRf5CACLjZwzQf4Br8jyh1gJ5fsJRhsNEh8eug0NHO7joCmjBpm0NFDfwx01HAGS6u2ro-_oXSkUQ.XrmZ4Q.-ZTZRG_ny9EArr_c8_oJi4ev1_0')])
May 12 04:30:59 katelyngigante uwsgi[1843]: Endpoint: cmc_chart
May 12 04:30:59 katelyngigante uwsgi[1843]: View Args: {'deck_id': '75698'}
May 12 04:30:59 katelyngigante uwsgi[1843]: Person: 688922828929499255
May 12 04:30:59 katelyngigante uwsgi[1843]: Referrer: https://pennydreadfulmagic.com/decks/75698/
May 12 04:30:59 katelyngigante uwsgi[1843]: Request Data: {}
May 12 04:30:59 katelyngigante uwsgi[1843]: Host: pennydreadfulmagic.com
May 12 04:30:59 katelyngigante uwsgi[1843]: Accept-Encoding: gzip
May 12 04:30:59 katelyngigante uwsgi[1843]: Cf-Ipcountry: US
May 12 04:30:59 katelyngigante uwsgi[1843]: X-Forwarded-For: 68.190.34.162, 172.69.22.196
May 12 04:30:59 katelyngigante uwsgi[1843]: Cf-Ray: 591df9604a0dd310-SJC
May 12 04:30:59 katelyngigante uwsgi[1843]: X-Forwarded-Proto: https
May 12 04:30:59 katelyngigante uwsgi[1843]: Cf-Visitor: {"scheme":"https"}
May 12 04:30:59 katelyngigante uwsgi[1843]: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
May 12 04:30:59 katelyngigante uwsgi[1843]: Accept: image/webp,image/apng,image/*,*/*;q=0.8
May 12 04:30:59 katelyngigante uwsgi[1843]: Sec-Fetch-Site: same-origin
May 12 04:30:59 katelyngigante uwsgi[1843]: Sec-Fetch-Mode: no-cors
May 12 04:30:59 katelyngigante uwsgi[1843]: Sec-Fetch-Dest: image
May 12 04:30:59 katelyngigante uwsgi[1843]: Referer: https://pennydreadfulmagic.com/decks/75698/
May 12 04:30:59 katelyngigante uwsgi[1843]: Accept-Language: en-US,en;q=0.9
May 12 04:30:59 katelyngigante uwsgi[1843]: Cookie: __cfduid=d2f9729cebf6ecae8cac1d9f7e22a9e2f1589221366; _ga=GA1.2.1298548655.1589221369; _gid=GA1.2.677192905.1589221369; _gat_gtag_UA_109131120_1=1; deck_id=75698; session=.eJx1UU1PwzAM_S85l6lNuy3djVEmEEJodLABQlXWpmlGk1RJCvvQ_jvupK0HxCWyn_387JcDyhpmJFVMOTRxpmUeooUUCk1KWlvICiaF1EWfC5trU2QCIDQiJMaYYHjjKI7xcIj6jlrntGbQxdTVSwqF_ylCZbwVdXFeodacs6JbzWp1kgqjmHhIOq6z1jKjqOwm72lelcDXtHUVzqyjroOTgszmq826xJFOlvN0MaaljPzlsglvX-77fqe_GFx6QDTPmbXnHD0-R_gu1Nw5O02fdIL5K1f7tVJjPH_zgc-2jTDMZhRMC4YkJngUkGAQEhJgHPb1zseRHxHf95BhJUDVRUQW8bd8x9dt3FarWfuTKv0gtklEbzRf5CACLjZwzQf4Br8jyh1gJ5fsJRhsNEh8eug0NHO7joCmjBpm0NFDfwx01HAGS6u2ro-_oXSkUQ.XrmZ4Q.-ZTZRG_ny9EArr_c8_oJi4ev1_0
May 12 04:30:59 katelyngigante uwsgi[1843]: Cf-Request-Id: 02a69a30300000d3102a9ed200000001
May 12 04:30:59 katelyngigante uwsgi[1843]: Cf-Connecting-Ip: 68.190.34.162
May 12 04:30:59 katelyngigante uwsgi[1843]: Cdn-Loop: cloudflare
May 12 04:30:59 katelyngigante uwsgi[1843]: X-Forwarded-Host: pennydreadfulmagic.com
May 12 04:30:59 katelyngigante uwsgi[1843]: X-Forwarded-Server: pennydreadfulmagic.com
May 12 04:30:59 katelyngigante uwsgi[1843]: Connection: Keep-Alive
May 12 04:30:59 katelyngigante uwsgi[1843]: ```
May 12 04:30:59 katelyngigante uwsgi[1843]: </details>
```

**Comment by bakert** [comment]
Probably just a one-off so closing but logging for future search.
