### ISSUE TITLE
Error during Post Rotation

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#7906]
```python traceback
Updating Legalities…
Traceback (most recent call last):
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f3246b3ef40>, 'Connection to api.github.com timed out. (connect timeout=15)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/discord/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/discord/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/PennyDreadfulMTG/perf-reports (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3246b3ef40>, 'Connection to api.github.com timed out. (connect timeout=15)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 174, in <module>
    cli()
  File "/home/discord/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/discord/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/discord/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/discord/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/discord/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 73, in maintenance
    task(['maintenance', script])
  File "run.py", line 125, in task
    exitcode = s.ad_hoc()  # type: ignore
  File "/home/discord/decksite/maintenance/post_rotation.py", line 30, in ad_hoc
    reprime_cache.run() # Update deck legalities
  File "/home/discord/decksite/maintenance/reprime_cache.py", line 16, in run
    card.preaggregate()
  File "/home/discord/decksite/decksite/data/card.py", line 34, in preaggregate
    preaggregate_card()
  File "/home/discord/decksite/decksite/data/card.py", line 84, in preaggregate_card
    preaggregation.preaggregate(table, sql)
  File "/home/discord/decksite/decksite/data/preaggregation.py", line 13, in preaggregate
    db().execute(sql)
  File "/home/discord/decksite/shared/database.py", line 48, in execute
    [n, _] = self.execute_anything(sql, args, False)
  File "/home/discord/decksite/shared/database.py", line 55, in execute_anything
    return self.execute_with_reconnect(sql, args, fetch_rows)
  File "/home/discord/decksite/shared/database.py", line 72, in execute_with_reconnect
    perf.check(p, 'slow_query', (f'```{sql}```', f'```{args}```'), 'mysql')
  File "/home/discord/decksite/shared/perf.py", line 22, in check
    repo.create_issue(msg, f'{location}-perf', flask_location or location, 'PennyDreadfulMTG/perf-reports')
  File "/home/discord/decksite/shared/repo.py", line 79, in create_issue
    git_repo = g.get_repo(repo_name)
  File "/home/discord/.local/lib/python3.8/site-packages/github/MainClass.py", line 333, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/discord/.local/lib/python3.8/site-packages/github/Requester.py", line 318, in requestJsonAndCheck
    *self.requestJson(
  File "/home/discord/.local/lib/python3.8/site-packages/github/Requester.py", line 410, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/discord/.local/lib/python3.8/site-packages/github/Requester.py", line 486, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/discord/.local/lib/python3.8/site-packages/github/Requester.py", line 513, in __requestRaw
    response = cnx.getresponse()
  File "/home/discord/.local/lib/python3.8/site-packages/github/Requester.py", line 110, in getresponse
    r = verb(
  File "/home/discord/.local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/discord/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/discord/.local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/discord/.local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/PennyDreadfulMTG/perf-reports (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3246b3ef40>, 'Connection to api.github.com timed out. (connect timeout=15)'))
```

**Comment by bakert** [comment]
@silasary as there has been a bunch of rotations since this I assume this is ok to close?
