### ISSUE TITLE
Charts do not work on Production

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#817]
Apparently the way we generate charts has a dependency on TCL/TKinder/X11

```
Traceback (most recent call last):
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discord/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discord/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/discord/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/discord/decksite/decksite/main.py", line 165, in cmc_chart
    return send_file(chart.cmc(int(deck_id)))
  File "/home/discord/decksite/decksite/charts/chart.py", line 25, in cmc
    image(path, costs)
  File "/home/discord/decksite/decksite/charts/chart.py", line 35, in image
    g = sns.barplot(ys, xs, palette=['grey'] * x_high)
  File "/home/discord/.local/lib/python3.5/site-packages/seaborn/categorical.py", line 2902, in barplot
    ax = plt.gca()
  File "/home/discord/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/home/discord/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/home/discord/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/discord/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/discord/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib64/python3.5/tkinter/__init__.py", line 1867, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by bakert** [comment]
I fixed this.
